// const journeyRegionCategories = [
//   '강원',
//   '경기',
//   '경남',
//   '경북',
//   '광주',
//   '대구',
//   '대전',
//   '부산',
//   '서울',
//   '세종',
//   '울산',
//   '인천',
//   '전남',
//   '전북',
//   '충남',
//   '충북',
//   '제주',
// ];

const journeyRegionCategories = {
  GANGWON: '강원',
  GYEONGGI: '경기',
  GYEONGNAM: '경남',
  GYEONGBUK: '경북',
  GWANGJU: '광주',
  DAEGU: '대구',
  DAEJEON: '대전',
  BUSAN: '부산',
  SEOUL: '서울',
  SEJONG: '세종',
  ULSAN: '울산',
  INCHEON: '인천',
  JEONNAM: '전남',
  JEONBUK: '전북',
  CHUNGNAM: '충남',
  CHUNGBUK: '충북',
  JEJU: '제주',
};

export default journeyRegionCategories;
