const comment = [
  {
    commentId: 1,
    memberId: '평화로운바다',
    memberName: 'han',
    placeId: 1,
    comment: '재미있어요',
    thumbnail: 'https://t1.daumcdn.net/thumb/R720x0/?fname=http://t1.daumcdn.net/brunch/service/user/5xq2/image/0lp8RLaJ2IgctTWVl2nEa-JRCSc.jpg',
  },
  {
    commentId: 2,
    memberId: '해바라기',
    memberName: 'kim',
    placeId: 1,
    comment: '황금시대를 보배를 곧 황금시대다. 평화스러운 피가 보이는 끓는다. 방황하였으며, 별과 이 현저하게 오직 끓는다. 얼마나 지혜는 뜨거운지라, 수 얼음 이상 쓸쓸하랴? 보내는 같은 예수는 없는 청춘을 인생에 위하여서. 하는 희망의 용기가 꽃 같지 무엇을 인간은 아니다. 전인 돋고, 찬미를 간에 때에, 이것이다. 이상은 우리 바로 인생을 싶이 새가 피부가 풍부하게 뿐이다. 피가 끝에 사랑의 작고 무한한 인생에 하는 봄바람을 때에, 힘있다. 불어 청춘 얼음이 내려온 천하를 충분히 것이다. 같이, 가치를 무엇이 뜨고, 그들의 아니다.',
    thumbnail: 'https://blog.kakaocdn.net/dn/cdISNs/btq80nGi2xw/yTgeawQCRLqZrEeSyv4VYK/img.jpg',
  },
  {
    commentId: 3,
    memberId: '단풍구경잼',
    memberName: 'han',
    placeId: 1,
    comment: '노잼',
    thumbnail: 'https://pds.joongang.co.kr/news/component/htmlphoto_mmdata/202210/21/bdd2abba-13c5-4a87-a50b-0d1c20b05f27.jpg',
  },
  {
    commentId: 4,
    memberId: '유잼러',
    memberName: 'lee',
    placeId: 1,
    comment: '유잼인가요?',
    thumbnail: 'https://img.sbs.co.kr/newimg/news/20160711/200959056_500.jpg',
  },
  {
    commentId: 5,
    memberId: '자연이좋아',
    memberName: 'park',
    placeId: 1,
    comment: '평화스러운 피가 보이는 끓는다.',
    thumbnail: 'https://t1.daumcdn.net/cfile/tistory/214DCD42594CC40625',
  },
  {
    commentId: 6,
    memberId: '자연이좋아',
    memberName: 'park',
    placeId: 1,
    comment: '평화스러운 피가 보이는 끓는다.',
    thumbnail: 'https://t1.daumcdn.net/cfile/tistory/214DCD42594CC40625',
  },
  {
    commentId: 7,
    memberId: '자연이좋아',
    memberName: 'park',
    placeId: 1,
    comment: '평화스러운 피가 보이는 끓는다.',
    thumbnail: 'https://t1.daumcdn.net/cfile/tistory/214DCD42594CC40625',
  },
  {
    commentId: 8,
    memberId: '자연이좋아',
    memberName: 'park',
    placeId: 1,
    comment: '평화스러운 피가 보이는 끓는다.',
    thumbnail: 'https://t1.daumcdn.net/cfile/tistory/214DCD42594CC40625',
  },
  {
    commentId: 9,
    memberId: '자연이좋아',
    memberName: 'park',
    placeId: 1,
    comment: '평화스러운 피가 보이는 끓는다.',
    thumbnail: 'https://t1.daumcdn.net/cfile/tistory/214DCD42594CC40625',
  },
  {
    commentId: 10,
    memberId: '자연이좋아',
    memberName: 'park',
    placeId: 1,
    comment: '평화스러운 피가 보이는 끓는다.',
    thumbnail: 'https://t1.daumcdn.net/cfile/tistory/214DCD42594CC40625',
  },
];

export default comment;
